version: "3"
services:
    db:
      image: postgres:14.1-alpine
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5432:5432'
      volumes: 
        - /var/lib/postgresql/data
      networks:
        - mynetwork

    server:
      build:
        context: ./server
        dockerfile: Dockerfile.server
      restart: always
      ports:
        - "4000:4000"
      volumes:
        - /app/node_modules
      networks:
        - mynetwork
      depends_on:
        - db
      command: >
       sh -c "npx prisma migrate dev --name init
       && npx prisma db seed
       && npm run dev"  
     
    client:
      build:
        context: ./client
        dockerfile: Dockerfile.client
      volumes:
        - /app/node_modules
        - ./client:/app
      ports:
        - "5173:5173"
      networks:
        - mynetwork
      depends_on:
        - db


networks:
    mynetwork: